server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      #List 형태로 여러가지 라우터 정보 등록 가능
      #path 로 오는 모든 요청은 uri 에서 처리
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**

        - id: first-service
          uri: lb://FIRST-SERVICE
          # 조건
          predicates:
            - Path=/first-service/**
          filters:
#            - AddRequestHeader=first-request, first-request-headerValue2
#            - AddResponseHeader=first-response, first-response-headerValue2
            - CustomFilter

        - id: second-service
          uri: lb://SECOND-SERVICE
          # 조건
          predicates:
            - Path=/second-service/**
          filters:
#            - AddRequestHeader=second-request, second-request-headerValue2
#            - AddResponseHeader=second-response, second-response-headerValue2
            - name: CustomFilter
            # 추가적인 파라미터를 넣으려면 - name 을 앞에 적어야지 구분 가능
            - name: LoggingFilter
              args:
                baseMessage: This is Logging Filter
                preLogger: true
                postLogger: true
