server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    #eureka 서버에 등록 가능 설정
    register-with-eureka: true
    #외부 에서 검색 가능한 형태로 만듬
    fetch-registry: true
    #eureka 서버의 위치 폴더를 지정
    service-url:
      #eureka 라는 엔드포인트에 현재 마이크로서비스를 등록
      defaultZone: http://127.0.0.1:8761/eureka
