server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  instance:
    #spring cloud 호스트 이름(ip), spring application 의 인스턴스 id 값, 포트를 랜덤하게 지정
   instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    #eureka 서버에 등록 가능 설정
    register-with-eureka: true
    #외부 에서 검색 가능한 형태로 만듬
    fetch-registry: true
    #eureka 서버의 위치 폴더를 지정
    service-url:
      #eureka 라는 엔드포인트에 현재 마이크로서비스를 등록
      defaultZone: http://127.0.0.1:8761/eureka
