server:
  port: 8888

spring:
  application:
    # application 이름 적용
    name: config-service
  cloud:
    config:
      server:
        git:
          # spring-config 생성한 깃 저장소 주소
          uri: file:///Users/leebeomjun/desktop/git/spring-cloud-config
